// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FastFileSwitcher
{
    internal sealed partial class Vsix
    {
        public const string Id = "FastFileSwitcher.c3f15831-2ce1-44bc-a4d2-cc1d27a148d2";
        public const string Name = "FastFileSwitcher";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
