// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FastFileSwitcher
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FastFileSwitcherString = "b0682221-b6a6-49ce-96c6-0897fd231408";
        public static Guid FastFileSwitcher = new Guid(FastFileSwitcherString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int DropdownMenuGroup = 0x0002;
        public const int AddFileCommand = 0x0100;
        public const int DisplayFilesCommand = 0x0200;
        public const int SwitchToFileCommand = 0x0300;
        public const int SwitchToFile1 = 0x0400;
        public const int SwitchToFile2 = 0x0500;
        public const int SwitchToFile3 = 0x0600;
        public const int SwitchToFile4 = 0x0700;
        public const int SwitchToFile5 = 0x0800;
        public const int SwitchToFile6 = 0x0900;
        public const int SwitchToFile7 = 0x1000;
        public const int SwitchToFile8 = 0x1100;
        public const int SwitchToFile9 = 0x1200;
    }
}